import Head from "next/head";
import { useDispatch, useSelector } from "react-redux";
import {
  data_list,
  set_toast_message,
  set_toast_status,
  set_toast_time_out,
} from "../root/commonSlice";
import { useEffect, useState } from "react";
import { useRouter } from "next/router";

export default function Home() {
  const dispatch = useDispatch();
  const router = useRouter();
  const [dataList, setDataList] = useState({});
  const data = useSelector(data_list);

  useEffect(() => {
    if (data) {
      setDataList(data);
    }
  }, [data]);

  return (
    <>
      <Head>
        <title>Home</title>
        <meta name="description" content="Generated by home" />
      </Head>

      <main className={"main"}>
        <button
          className={
            "inline-block text-center m-2 bg-blue-500 hover:bg-blue-700 focus:bg-green-700 text-white font-bold py-2 px-4 rounded"
          }
          onClick={() => {
            dispatch(set_toast_status(2));
            dispatch(set_toast_message(`Please waiting ...`));
            dispatch(set_toast_time_out(3000));
            setTimeout(() => {
              dispatch(set_toast_status(1));
              dispatch(set_toast_message(`Save successfully!`));
            }, 1000);
          }}
        >
          Show Toast Successfully
        </button>
        <button
          className={
            "inline-block text-center m-2 bg-blue-500 hover:bg-blue-700 focus:bg-green-700 text-white font-bold py-2 px-4 rounded"
          }
          onClick={() => {
            dispatch(set_toast_status(2));
            dispatch(set_toast_message(`Please waiting ...`));
            dispatch(set_toast_time_out(3000));
            setTimeout(() => {
              dispatch(set_toast_status(0));
              dispatch(set_toast_message(`Saving failed, please try again`));
            }, 1000);
          }}
        >
          Show Toast Fail
        </button>
        <button
          className={
            "inline-block text-center m-2 bg-blue-500 hover:bg-blue-700 focus:bg-green-700 text-white font-bold py-2 px-4 rounded"
          }
          onClick={() => {
            router.push("/login");
          }}
        >
          Login Form
        </button>
        <br />
        <br />
        <a
          href={"/api"}
          style={{ color: "#0dd" }}
          target="_blank"
          rel="noreferrer"
        >
          /api
        </a>
        <br />
        <a
          href={"/api/users/login"}
          style={{ color: "red" }}
          target="_blank"
          rel="noreferrer"
        >
          /api/users/login
        </a>
        <br />
        <br />
        common.data_list : {JSON.stringify(dataList)}
        <br />
        <br />
        <button
          onClick={() => {
            dispatch({ type: "SAGA_GET_DATA_LIST", url: "/api/users/login" });
          }}
        >
          [GET] /api/users/login
        </button>
        <br />
        <button
          onClick={() => {
            dispatch({ type: "SAGA_GET_DATA_LIST", url: "/api" });
          }}
        >
          [GET] /api
        </button>
      </main>
    </>
  );
}
